# Celebal Technologies Internship

## Assignment 03

### Advanced SQL using Subqueries, CTEs & Window Functions

**Name:** Prachurya Nanda

**Role:** Data Engineer Intern

In [1]:
!pip install mysql-connector-python pandas

Requirement already satisfied: mysql-connector-python in c:\users\prapt\appdata\local\programs\python\python310\lib\site-packages (9.7.0)
Requirement already satisfied: pandas in c:\users\prapt\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\prapt\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prapt\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prapt\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prapt\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\prapt\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'C:\Users\prapt\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [2]:
import mysql.connector
import pandas as pd

In [3]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="gayPrince8$",
    database="superstore_week3"
)

print("✅ Connected to MySQL Successfully!")

✅ Connected to MySQL Successfully!

In [4]:
def run_query(query):
    df = pd.read_sql(query, conn)
    return df

In [5]:
query = "SHOW TABLES;"
run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

  Tables_in_superstore_week3
0                  customers
1                     orders
2                   products
3                 superstore

# Step 1: Setup Data

## Objective

Create normalized tables (`customers`, `orders`, and `products`) from the Superstore dataset using `SELECT DISTINCT`.

In [6]:
query = """
SELECT * FROM customers LIMIT 5;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,Customer ID,Customer Name,Segment,Country,City,State,Region
0,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South
1,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West
2,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
3,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
4,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,South

In [7]:
query = """
SELECT * FROM orders LIMIT 5;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Product ID,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,FUR-BO-10001798,261.9600,2,0.00,41.9136
1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,FUR-CH-10000454,731.9400,3,0.00,219.5820
2,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,OFF-LA-10000240,14.6200,2,0.00,6.8714
3,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,FUR-TA-10000577,957.5775,5,0.45,-383.0310
4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,OFF-ST-10000760,22.3680,2,0.20,2.5164

In [8]:
query = """
SELECT * FROM products LIMIT 5;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,Product ID,Category,Sub-Category,Product Name
0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase
1,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...
3,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table
4,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System

# Question 1: Orders with Sales Greater than Average

## Objective

Retrieve all orders where the sales amount is greater than the average sales using a subquery.

In [9]:
query = """
SELECT
    `Order ID`,
    `Customer ID`,
    Sales
FROM orders
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM orders
);
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

            Order ID Customer ID      Sales
0     CA-2016-152156    CG-12520   261.9600
1     CA-2016-152156    CG-12520   731.9400
2     US-2015-108966    SO-20335   957.5775
3     CA-2014-115812    BH-11710   907.1520
4     CA-2014-115812    BH-11710  1706.1840
...              ...         ...        ...
2301  US-2016-103674    AP-10720   271.9600
2302  US-2016-103674    AP-10720   249.5840
2303  US-2016-103674    AP-10720   437.4720
2304  CA-2017-121258    DB-13060   258.5760
2305  CA-2017-119914    CC-12220   243.1600

[2306 rows x 3 columns]

### Observation

This query retrieves all orders whose sales value is greater than the average sales across all orders. It demonstrates the use of a subquery in the WHERE clause for comparison.

# Question 2: Highest Sales Order for Each Customer

## Objective

Identify the highest sales order placed by each customer using a correlated subquery.

In [10]:
query = """
SELECT
    o.`Order ID`,
    o.`Customer ID`,
    o.Sales
FROM orders o
JOIN
(
    SELECT
        `Customer ID`,
        MAX(Sales) AS Max_Sales
    FROM orders
    GROUP BY `Customer ID`
) m
ON o.`Customer ID` = m.`Customer ID`
AND o.Sales = m.Max_Sales;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

           Order ID Customer ID      Sales
0    CA-2016-152156    CG-12520   731.9400
1    US-2015-108966    SO-20335   957.5775
2    CA-2014-115812    BH-11710  1706.1840
3    CA-2015-106320    EB-13870  1044.6300
4    US-2015-150630    TB-21520  3083.4300
..              ...         ...        ...
790  CA-2015-159534    DH-13075  1087.9360
791  CA-2016-129630    IM-15055  2799.9600
792  CA-2017-121559    HW-14935  2405.2000
793  CA-2017-153871    RB-19435   735.9800
794  US-2016-103674    AP-10720   437.4720

[795 rows x 3 columns]

### Observation

The query identifies the highest-value order placed by each customer using a correlated subquery.

# Question 3: Calculate Total Sales per Customer using a CTE

## Objective

Use a Common Table Expression (CTE) to calculate the total sales for each customer.

In [11]:
query = """
WITH CustomerSales AS
(
    SELECT
        `Customer ID`,
        ROUND(SUM(Sales), 2) AS Total_Sales
    FROM orders
    GROUP BY `Customer ID`
)

SELECT *
FROM CustomerSales;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

    Customer ID  Total_Sales
0      CG-12520      1148.78
1      DV-13045      1119.48
2      SO-20335      2602.58
3      BH-11710      6255.35
4      AA-10480      1782.87
..          ...          ...
788    CJ-11875        16.52
789    RS-19870        22.33
790    SC-20845       280.63
791    RE-19405        48.36
792    SM-20905      1043.04

[793 rows x 2 columns]

### Observation

The Common Table Expression (CTE) calculates the total sales for each customer, making the query more readable and reusable for further analysis.

# Question 4: Customers with Above Average Total Sales

## Objective

Identify customers whose total sales are greater than the average customer sales using a CTE and subquery.

In [12]:
query = """
WITH CustomerSales AS
(
    SELECT
        `Customer ID`,
        ROUND(SUM(Sales), 2) AS Total_Sales
    FROM orders
    GROUP BY `Customer ID`
)

SELECT *
FROM CustomerSales
WHERE Total_Sales >
(
    SELECT AVG(Total_Sales)
    FROM CustomerSales
);
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

    Customer ID  Total_Sales
0      BH-11710      6255.35
1      IM-15070      4930.47
2      PK-19075      8158.65
3      TB-21520      4730.63
4      MA-17560      4280.62
..          ...          ...
294    SB-20185      6411.00
295    TS-21655      3368.09
296    VP-21760      3193.61
297    CM-12715      3984.45
298    LC-16960      3246.63

[299 rows x 2 columns]

### Observation

The query identifies customers whose total sales exceed the average customer sales, helping to recognize high-value customers.

# Question 5: Rank Customers based on Total Sales

## Objective

Use the RANK() window function to rank customers according to their total sales.

In [13]:
query = """
WITH CustomerSales AS
(
    SELECT `Customer ID`, ROUND(SUM(Sales), 2) AS Total_Sales
    FROM orders
    GROUP BY `Customer ID`
)

SELECT
    `Customer ID`,
    Total_Sales,
    RANK() OVER (ORDER BY Total_Sales DESC) AS Customer_Rank
FROM CustomerSales;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

    Customer ID  Total_Sales  Customer_Rank
0      SM-20320     25043.05              1
1      TC-20980     19017.85              2
2      RB-19360     15117.34              3
3      TA-21385     14595.62              4
4      AB-10105     14355.61              5
..          ...          ...            ...
788    RS-19870        22.33            789
789    CJ-11875        16.52            790
790    MG-18205        12.32            791
791    LD-16855         5.30            792
792    TS-21085         4.83            793

[793 rows x 3 columns]

### Observation

The RANK() window function assigns rankings based on total sales, allowing easy identification of top-performing customers.

# Question 6: Assign Row Numbers to Orders

## Objective

Use the ROW_NUMBER() window function to assign a unique sequential number to each order.

In [14]:
query = """
SELECT `Customer ID`,`Order ID`,`Order Date`, Sales,
    ROW_NUMBER() OVER
    (
        PARTITION BY `Customer ID`
        ORDER BY `Order Date`
    ) AS Order_Number
FROM orders;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

     Customer ID        Order ID  Order Date     Sales  Order_Number
0       AA-10315  CA-2016-103982  03-03-2016   431.976             1
1       AA-10315  CA-2016-103982  03-03-2016    41.720             2
2       AA-10315  CA-2016-103982  03-03-2016  3930.072             3
3       AA-10315  CA-2016-103982  03-03-2016     2.304             4
4       AA-10315  CA-2015-121391  10-04-2015    26.960             5
...          ...             ...         ...       ...           ...
9688    ZD-21925  CA-2016-152471  07-08-2016   823.960             5
9689    ZD-21925  CA-2016-152471  07-08-2016    15.984             6
9690    ZD-21925  CA-2014-143336   8/27/2014    22.720             7
9691    ZD-21925  CA-2014-143336   8/27/2014   213.480             8
9692    ZD-21925  CA-2014-143336   8/27/2014     8.560             9

[9693 rows x 5 columns]

### Observation

ROW_NUMBER() assigns a unique sequential number to each row, which is useful for ordering and identifying records.

# Question 7: Top 3 Customers by Sales

## Objective

Retrieve the top three customers based on total sales using window functions.

In [15]:
query = """
WITH CustomerSales AS
(
    SELECT `Customer ID`, ROUND(SUM(Sales), 2) AS Total_Sales
    FROM orders
    GROUP BY `Customer ID`
),

CustomerRanking AS
(
    SELECT `Customer ID`, Total_Sales,
        RANK() OVER (ORDER BY Total_Sales DESC) AS Customer_Rank
    FROM CustomerSales
)

SELECT *
FROM CustomerRanking
WHERE Customer_Rank <= 3;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

  Customer ID  Total_Sales  Customer_Rank
0    SM-20320     25043.05              1
1    TC-20980     19017.85              2
2    RB-19360     15117.34              3

### Observation

The query identifies the top three customers with the highest sales, demonstrating the practical use of ranking functions for business analysis.

# Final Combined Query

## Objective

Combine JOIN, Common Table Expressions (CTEs), and Window Functions to generate a ranked customer sales report showing customer names, total sales, and customer rankings.

In [16]:
query = """
WITH CustomerSales AS
(
    SELECT `Customer ID`, ROUND(SUM(Sales), 2) AS Total_Sales
    FROM orders
    GROUP BY `Customer ID`
)

SELECT c.`Customer Name`, cs.Total_Sales,
    RANK() OVER (ORDER BY cs.Total_Sales DESC) AS Customer_Rank
FROM CustomerSales cs
JOIN customers c
ON cs.`Customer ID` = c.`Customer ID`
ORDER BY Customer_Rank;
"""

run_query(query)

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

        Customer Name  Total_Sales  Customer_Rank
0         Sean Miller     25043.05              1
1         Sean Miller     25043.05              1
2         Sean Miller     25043.05              1
3         Sean Miller     25043.05              1
4         Sean Miller     25043.05              1
...               ...          ...            ...
4617     Carl Jackson        16.52           4618
4618  Mitch Gastineau        12.32           4619
4619     Lela Donovan         5.30           4620
4620    Thais Sissman         4.83           4621
4621    Thais Sissman         4.83           4621

[4622 rows x 3 columns]

### Observation

This query combines JOINs, CTEs, and Window Functions to produce a comprehensive customer sales report. It ranks customers based on their total sales and demonstrates the practical use of multiple advanced SQL concepts in a single query.

# Mini Project

## Business Analysis using the Superstore Dataset

### Objective

Apply advanced SQL concepts to solve real-world business problems using the Superstore dataset.

### Business Questions

1. Identify the Top 5 Customers based on Total Sales.
2. Identify the Bottom 5 Customers based on Total Sales.
3. Find Customers Who Placed Only One Order.
4. Identify Customers with Above Average Total Sales.
5. Find the Highest Order Value for Each Customer.

In [17]:
from IPython.display import display

print("="*80)
print("Business Question 1: Top 5 Customers based on Total Sales")
print("="*80)

query = """
SELECT
    `Customer ID`,
    `Customer Name`,
    ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY `Customer ID`, `Customer Name`
ORDER BY Total_Sales DESC
LIMIT 5;
"""

display(run_query(query))


print("="*80)
print("Business Question 2: Bottom 5 Customers based on Total Sales")
print("="*80)

query = """
SELECT
    `Customer ID`,
    `Customer Name`,
    ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY `Customer ID`, `Customer Name`
ORDER BY Total_Sales ASC
LIMIT 5;
"""

display(run_query(query))


print("="*80)
print("Business Question 3: Customers Who Placed Only One Order")
print("="*80)

query = """
SELECT
    `Customer ID`,
    `Customer Name`,
    COUNT(DISTINCT `Order ID`) AS Total_Orders
FROM superstore
GROUP BY `Customer ID`, `Customer Name`
HAVING COUNT(DISTINCT `Order ID`) = 1;
"""

display(run_query(query))


print("="*80)
print("Business Question 4: Customers with Above Average Total Sales")
print("="*80)

query = """
WITH CustomerSales AS
(
    SELECT
        `Customer ID`,
        `Customer Name`,
        ROUND(SUM(Sales),2) AS Total_Sales
    FROM superstore
    GROUP BY `Customer ID`, `Customer Name`
)

SELECT *
FROM CustomerSales
WHERE Total_Sales >
(
    SELECT AVG(Total_Sales)
    FROM CustomerSales
)
ORDER BY Total_Sales DESC;
"""

display(run_query(query))


print("="*80)
print("Business Question 5: Highest Order Value for Each Customer")
print("="*80)

query = """
SELECT
    `Customer ID`,
    `Customer Name`,
    ROUND(MAX(Sales),2) AS Highest_Order_Value
FROM superstore
GROUP BY `Customer ID`, `Customer Name`
ORDER BY Highest_Order_Value DESC;
"""

display(run_query(query))

================================================================================
Business Question 1: Top 5 Customers based on Total Sales
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

  Customer ID  Customer Name  Total_Sales
0    SM-20320    Sean Miller     25043.05
1    TC-20980   Tamara Chand     19017.85
2    RB-19360   Raymond Buch     15117.34
3    TA-21385   Tom Ashbrook     14595.62
4    AB-10105  Adrian Barton     14355.61

================================================================================
Business Question 2: Bottom 5 Customers based on Total Sales
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

  Customer ID    Customer Name  Total_Sales
0    TS-21085    Thais Sissman         4.83
1    LD-16855     Lela Donovan         5.30
2    MG-18205  Mitch Gastineau        12.32
3    CJ-11875     Carl Jackson        16.52
4    RS-19870       Roy Skaria        22.33

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

================================================================================
Business Question 3: Customers Who Placed Only One Order
================================================================================

   Customer ID      Customer Name  Total_Orders
0     AO-10810  Anthony O'Donnell             1
1     AR-10570     Anemone Ratner             1
2     CJ-11875       Carl Jackson             1
3     JC-15385       Jenna Caffey             1
4     JR-15700     Jocasta Rupert             1
5     LD-16855       Lela Donovan             1
6     MG-18205    Mitch Gastineau             1
7     PH-18790  Patricia Hirasaki             1
8     RE-19405    Ricardo Emerson             1
9     RM-19750      Roland Murray             1
10    SM-20905  Susan MacKendrick             1
11    TC-21145      Theresa Coyne             1

================================================================================
Business Question 4: Customers with Above Average Total Sales
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

    Customer ID      Customer Name  Total_Sales
0      SM-20320        Sean Miller     25043.05
1      TC-20980       Tamara Chand     19017.85
2      RB-19360       Raymond Buch     15117.34
3      TA-21385       Tom Ashbrook     14595.62
4      AB-10105      Adrian Barton     14355.61
..          ...                ...          ...
294    MT-17815        Meg Tillman      2890.14
295    DS-13180        David Smith      2881.81
296    PV-18985      Paul Van Hugh      2876.05
297    CC-12430        Chuck Clark      2870.05
298    BF-11020  Barry Französisch      2865.79

[299 rows x 3 columns]

================================================================================
Business Question 5: Highest Order Value for Each Customer
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_128704\1501860199.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

    Customer ID    Customer Name  Highest_Order_Value
0      SM-20320      Sean Miller             22638.48
1      TC-20980     Tamara Chand             17499.95
2      RB-19360     Raymond Buch             13999.96
3      TA-21385     Tom Ashbrook             11199.97
4      HL-15040     Hunter Lopez             10499.97
..          ...              ...                  ...
788    CJ-11875     Carl Jackson                16.52
789    MG-18205  Mitch Gastineau                12.32
790    RS-19870       Roy Skaria                 9.65
791    LD-16855     Lela Donovan                 5.30
792    TS-21085    Thais Sissman                 2.81

[793 rows x 3 columns]

# Conclusion

This assignment demonstrated the practical application of advanced SQL concepts, including Subqueries, Common Table Expressions (CTEs), Window Functions, and Joins, to analyze the Superstore dataset. The business analysis helped identify valuable customer trends and generated actionable insights for data-driven decision-making.