# E-Commerce Sales Database Analysis

## Celebal Technologies Internship - Week 2

**Name:** Prachurya Nanda

**Database:** MySQL

### Objective

To perform SQL queries on an E-Commerce Sales Database using MySQL and analyze customer, product, order and transaction data.

In [1]:
import pandas as pd
import mysql.connector

In [2]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="gayPrince8$",
    database="ecommerce_db"
)

cursor = connection.cursor()

print("Connected Successfully!")

Connected Successfully!

In [3]:
def run_assignment_query(title, query):
    print("\n" + "="*80)
    print(title)
    print("="*80)
    display(pd.read_sql(query, connection))

In [4]:
print("="*90)
print("SECTION A - SQL BASICS")
print("="*90)

run_assignment_query(
    "Q1. Display all columns and rows from the customers table",
    "SELECT * FROM customers;"
)

run_assignment_query(
    "Q2. Retrieve first_name, last_name and city",
    """
    SELECT first_name, last_name, city
    FROM customers;
    """
)

run_assignment_query(
    "Q3. List all unique product categories",
    """
    SELECT DISTINCT category
    FROM products;
    """
)

print("\n" + "="*90)
print("Q4. Primary Keys")
print("="*90)

print("""
customers    : customer_id
products     : product_id
orders       : order_id
order_items  : item_id

Explanation:
A Primary Key uniquely identifies each record.
It must be UNIQUE and NOT NULL.
""")

print("\n" + "="*90)
print("Q5. Email Constraints")
print("="*90)

print("""
Constraints:
• UNIQUE
• NOT NULL

Duplicate emails are not allowed.
""")

print("\n" + "="*90)
print("Q6. CHECK Constraint")
print("="*90)

try:
    cursor.execute("""
    INSERT INTO products
    VALUES
    (209,'Test Product','Electronics',
    'TestBrand',-50,100);
    """)
    connection.rollback()
except Exception as e:
    print("Expected Error:")
    print(e)

==========================================================================================
SECTION A - SQL BASICS
==========================================================================================

================================================================================
Q1. Display all columns and rows from the customers table
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

================================================================================
Q2. Retrieve first_name, last_name and city
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

  first_name last_name       city
0      Aarav    Sharma     Mumbai
1      Priya     Patel  Ahmedabad
2      Rohan     Gupta      Delhi
3      Sneha     Reddy  Hyderabad
4     Vikram     Singh     Jaipur
5     Ananya      Iyer    Chennai
6      Karan     Mehta       Pune
7      Divya      Nair      Kochi

================================================================================
Q3. List all unique product categories
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

      category
0  Electronics
1     Clothing
2         Home

==========================================================================================
Q4. Primary Keys
==========================================================================================

customers    : customer_id
products     : product_id
orders       : order_id
order_items  : item_id

Explanation:
A Primary Key uniquely identifies each record.
It must be UNIQUE and NOT NULL.


==========================================================================================
Q5. Email Constraints
==========================================================================================

Constraints:
• UNIQUE
• NOT NULL

Duplicate emails are not allowed.


==========================================================================================
Q6. CHECK Constraint
==========================================================================================
Expected Error:
3819 (HY000): Check constraint 'products_chk_1' is violated.

In [5]:
print("="*90)
print("SECTION B - FILTERING & OPTIMIZATION")
print("="*90)

# Q7
run_assignment_query(
    "Q7. Orders with status = 'Delivered'",
    """
    SELECT *
    FROM orders
    WHERE status = 'Delivered';
    """
)

# Q8
run_assignment_query(
    "Q8. Electronics products with unit_price > 2000",
    """
    SELECT *
    FROM products
    WHERE category='Electronics'
    AND unit_price>2000;
    """
)

# Q9
run_assignment_query(
    "Q9. Customers from Maharashtra who joined in 2024",
    """
    SELECT *
    FROM customers
    WHERE state='Maharashtra'
    AND YEAR(join_date)=2024;
    """
)

# Q10
run_assignment_query(
    "Q10. Orders placed between 2024-08-10 and 2024-08-25 excluding Cancelled",
    """
    SELECT *
    FROM orders
    WHERE order_date BETWEEN '2024-08-10' AND '2024-08-25'
    AND status<>'Cancelled';
    """
)

print("\n" + "="*90)
print("Q11. Purpose of idx_orders_date")
print("="*90)

print("""
The index 'idx_orders_date' improves the performance of queries
that search, filter or sort records using the order_date column.
It reduces the number of rows scanned and speeds up data retrieval.
""")

print("\n" + "="*90)
print("Q12. SARGable Query")
print("="*90)

print("""
Query:
SELECT * FROM customers
WHERE YEAR(join_date)=2024;

This query is NOT SARGable because YEAR() is applied on the indexed column.

A better version is:

SELECT *
FROM customers
WHERE join_date BETWEEN '2024-01-01' AND '2024-12-31';

This allows MySQL to use an index efficiently.
""")

==========================================================================================
SECTION B - FILTERING & OPTIMIZATION
==========================================================================================

================================================================================
Q7. Orders with status = 'Delivered'
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered        4498.0
1      1002          102  2024-08-03  Delivered         799.0
2      1004          101  2024-08-10  Delivered        3499.0
3      1006          105  2024-08-15  Delivered        5898.0
4      1008          103  2024-08-20  Delivered         899.0
5      1010          108  2024-08-28  Delivered        1598.0

================================================================================
Q8. Electronics products with unit_price > 2000
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

   product_id       product_name     category  brand  unit_price  stock_qty
0         203        Smart Watch  Electronics  Noise      2999.0        149
1         205  Bluetooth Speaker  Electronics    JBL      3499.0        200

================================================================================
Q9. Customers from Maharashtra who joined in 2024
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

================================================================================
Q10. Orders placed between 2024-08-10 and 2024-08-25 excluding Cancelled
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

   order_id  customer_id  order_date     status  total_amount
0      1004          101  2024-08-10  Delivered        3499.0
1      1006          105  2024-08-15  Delivered        5898.0
2      1007          106  2024-08-18    Pending        1299.0
3      1008          103  2024-08-20  Delivered         899.0
4      1009          107  2024-08-25    Shipped        6098.0

==========================================================================================
Q11. Purpose of idx_orders_date
==========================================================================================

The index 'idx_orders_date' improves the performance of queries
that search, filter or sort records using the order_date column.
It reduces the number of rows scanned and speeds up data retrieval.


==========================================================================================
Q12. SARGable Query
==========================================================================================

Query:
SELECT * FROM customers
WHERE YEAR(join_date)=2024;

This query is NOT SARGable because YEAR() is applied on the indexed column.

A better version is:

SELECT *
FROM customers
WHERE join_date BETWEEN '2024-01-01' AND '2024-12-31';

This allows MySQL to use an index efficiently.

In [6]:
print("="*90)
print("SECTION C - AGGREGATION")
print("="*90)

# Q13
run_assignment_query(
    "Q13. Count the total number of orders",
    """
    SELECT COUNT(*) AS Total_Orders
    FROM orders;
    """
)

# Q14
run_assignment_query(
    "Q14. Total revenue from Delivered orders",
    """
    SELECT SUM(total_amount) AS Total_Revenue
    FROM orders
    WHERE status='Delivered';
    """
)

# Q15
run_assignment_query(
    "Q15. Average unit price by category",
    """
    SELECT
        category,
        ROUND(AVG(unit_price),2) AS Average_Unit_Price
    FROM products
    GROUP BY category;
    """
)

# Q16
run_assignment_query(
    "Q16. Order count and revenue by status",
    """
    SELECT
        status,
        COUNT(*) AS Order_Count,
        ROUND(SUM(total_amount),2) AS Total_Revenue
    FROM orders
    GROUP BY status
    ORDER BY Total_Revenue DESC;
    """
)

# Q17
run_assignment_query(
    "Q17. Most expensive and cheapest product in each category",
    """
    SELECT
        category,
        MAX(unit_price) AS Highest_Price,
        MIN(unit_price) AS Lowest_Price
    FROM products
    GROUP BY category;
    """
)

# Q18
run_assignment_query(
    "Q18. Categories with average unit price greater than ₹2000",
    """
    SELECT
        category,
        ROUND(AVG(unit_price),2) AS Average_Unit_Price
    FROM products
    GROUP BY category
    HAVING AVG(unit_price) > 2000;
    """
)

==========================================================================================
SECTION C - AGGREGATION
==========================================================================================

================================================================================
Q13. Count the total number of orders
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

   Total_Orders
0            11

================================================================================
Q14. Total revenue from Delivered orders
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

   Total_Revenue
0        17191.0

================================================================================
Q15. Average unit price by category
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

      category  Average_Unit_Price
0  Electronics              2224.0
1     Clothing              2699.0
2         Home               949.0

================================================================================
Q16. Order count and revenue by status
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

      status  Order_Count  Total_Revenue
0  Delivered            6        17191.0
1    Shipped            2        13596.0
2  Cancelled            1         2999.0
3    Pending            2         2897.0

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

================================================================================
Q17. Most expensive and cheapest product in each category
================================================================================

      category  Highest_Price  Lowest_Price
0  Electronics         3499.0         899.0
1     Clothing         4599.0         799.0
2         Home         1299.0         599.0

================================================================================
Q18. Categories with average unit price greater than ₹2000
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

      category  Average_Unit_Price
0  Electronics              2224.0
1     Clothing              2699.0

In [7]:
print("="*90)
print("SECTION D - JOINS & RELATIONSHIPS")
print("="*90)

# Q19
run_assignment_query(
    "Q19. Display each order along with customer details",
    """
    SELECT
        o.order_id,
        o.order_date,
        c.first_name,
        c.last_name,
        o.total_amount
    FROM orders o
    INNER JOIN customers c
    ON o.customer_id = c.customer_id;
    """
)

# Q20
run_assignment_query(
    "Q20. Display all customers and their orders (if any)",
    """
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        o.order_id,
        o.order_date,
        o.total_amount
    FROM customers c
    LEFT JOIN orders o
    ON c.customer_id = o.customer_id;
    """
)

# Q21
run_assignment_query(
    "Q21. Display order details with product information",
    """
    SELECT
        o.order_id,
        p.product_name,
        oi.quantity,
        oi.unit_price,
        oi.discount_pct
    FROM orders o
    INNER JOIN order_items oi
    ON o.order_id = oi.order_id
    INNER JOIN products p
    ON oi.product_id = p.product_id;
    """
)

print("\n" + "="*90)
print("Q22. LEFT JOIN vs RIGHT JOIN")
print("="*90)

print("""
LEFT JOIN:
Returns all rows from the left table and matching rows from the right table.

RIGHT JOIN:
Returns all rows from the right table and matching rows from the left table.

FULL OUTER JOIN:
Returns all matching and non-matching rows from both tables.
MySQL does not support FULL OUTER JOIN directly.
It can be simulated using UNION of LEFT JOIN and RIGHT JOIN.
""")

print("\n" + "="*90)
print("Q23. Foreign Key Relationships")
print("="*90)

print("""
Foreign Keys:

orders.customer_id  --> customers.customer_id

order_items.order_id --> orders.order_id

order_items.product_id --> products.product_id

If customer_id = 999 is inserted into the orders table,
MySQL will reject the INSERT statement because of the
FOREIGN KEY constraint.
""")

==========================================================================================
SECTION D - JOINS & RELATIONSHIPS
==========================================================================================

================================================================================
Q19. Display each order along with customer details
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

    order_id  order_date first_name last_name  total_amount
0       1001  2024-08-01      Aarav    Sharma        4498.0
1       1004  2024-08-10      Aarav    Sharma        3499.0
2       1002  2024-08-03      Priya     Patel         799.0
3       1011  2026-06-28      Priya     Patel        1598.0
4       1003  2024-08-05      Rohan     Gupta        7498.0
5       1008  2024-08-20      Rohan     Gupta         899.0
6       1005  2024-08-12      Sneha     Reddy        2999.0
7       1006  2024-08-15     Vikram     Singh        5898.0
8       1007  2024-08-18     Ananya      Iyer        1299.0
9       1009  2024-08-25      Karan     Mehta        6098.0
10      1010  2024-08-28      Divya      Nair        1598.0

================================================================================
Q20. Display all customers and their orders (if any)
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

    customer_id first_name last_name  order_id  order_date  total_amount
0           101      Aarav    Sharma      1001  2024-08-01        4498.0
1           101      Aarav    Sharma      1004  2024-08-10        3499.0
2           102      Priya     Patel      1002  2024-08-03         799.0
3           102      Priya     Patel      1011  2026-06-28        1598.0
4           103      Rohan     Gupta      1003  2024-08-05        7498.0
5           103      Rohan     Gupta      1008  2024-08-20         899.0
6           104      Sneha     Reddy      1005  2024-08-12        2999.0
7           105     Vikram     Singh      1006  2024-08-15        5898.0
8           106     Ananya      Iyer      1007  2024-08-18        1299.0
9           107      Karan     Mehta      1009  2024-08-25        6098.0
10          108      Divya      Nair      1010  2024-08-28        1598.0

================================================================================
Q21. Display order details with product information
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

    order_id          product_name  quantity  unit_price  discount_pct
0       1011      Wireless Earbuds         1       999.0           0.0
1       1001      Wireless Earbuds         2      1499.0           0.0
2       1006      Wireless Earbuds         1      1499.0          10.0
3       1002        Cotton T-Shirt         1       799.0           0.0
4       1011           Smart Watch         1       599.0           0.0
5       1003           Smart Watch         1      2999.0           0.0
6       1005           Smart Watch         1      2999.0           0.0
7       1003         Running Shoes         1      4599.0           5.0
8       1006         Running Shoes         1      4599.0           5.0
9       1004     Bluetooth Speaker         1      3499.0           0.0
10      1009     Bluetooth Speaker         1      3499.0           0.0
11      1007          Bedsheet Set         1      1299.0           0.0
12      1010          Bedsheet Set         1      1299.0           0.0
13      1001          Laptop Stand         1       899.0          10.0
14      1008          Laptop Stand         1       899.0           0.0
15      1009  Cushion Covers (Set)         2       599.0          15.0
16      1010  Cushion Covers (Set)         1       599.0           0.0

==========================================================================================
Q22. LEFT JOIN vs RIGHT JOIN
==========================================================================================

LEFT JOIN:
Returns all rows from the left table and matching rows from the right table.

RIGHT JOIN:
Returns all rows from the right table and matching rows from the left table.

FULL OUTER JOIN:
Returns all matching and non-matching rows from both tables.
MySQL does not support FULL OUTER JOIN directly.
It can be simulated using UNION of LEFT JOIN and RIGHT JOIN.


==========================================================================================
Q23. Foreign Key Relationships
==========================================================================================

Foreign Keys:

orders.customer_id  --> customers.customer_id

order_items.order_id --> orders.order_id

order_items.product_id --> products.product_id

If customer_id = 999 is inserted into the orders table,
MySQL will reject the INSERT statement because of the
FOREIGN KEY constraint.

In [8]:
print("="*90)
print("SECTION E - ADVANCED CONCEPTS")
print("="*90)

# Q24
run_assignment_query(
    "Q24. Classify products into price tiers",
    """
    SELECT
        product_name,
        unit_price,
        CASE
            WHEN unit_price < 1000 THEN 'Budget'
            WHEN unit_price BETWEEN 1000 AND 3000 THEN 'Mid-Range'
            ELSE 'Premium'
        END AS price_tier
    FROM products;
    """
)

# Q25
run_assignment_query(
    "Q25. Count Delivered vs Not Delivered orders",
    """
    SELECT
        SUM(CASE WHEN status='Delivered' THEN 1 ELSE 0 END) AS Delivered,
        SUM(CASE WHEN status<>'Delivered' THEN 1 ELSE 0 END) AS Not_Delivered
    FROM orders;
    """
)

print("\n" + "="*90)
print("Q26. ACID Properties")
print("="*90)

print("""
A - Atomicity
A transaction is completed fully or not at all.

C - Consistency
The database remains valid before and after every transaction.

I - Isolation
Transactions execute independently without interfering.

D - Durability
Once committed, changes are permanently stored.

Example:
In a bank transfer, money is deducted from one account
and credited to another. If any step fails, the entire
transaction is rolled back.
""")

print("\n" + "="*90)
print("Q27. SQL Transaction")
print("="*90)

print("""
START TRANSACTION;

INSERT INTO orders
(order_id, customer_id, order_date, status, total_amount)
VALUES
(1011,102,CURDATE(),'Pending',1598.00);

INSERT INTO order_items
(item_id,order_id,product_id,quantity,unit_price,discount_pct)
VALUES
(16,1011,201,1,999.00,0),
(17,1011,203,1,599.00,0);

UPDATE products
SET stock_qty=stock_qty-1
WHERE product_id IN (201,203);

COMMIT;

If any statement fails before COMMIT,
ROLLBACK should be executed.
""")

==========================================================================================
SECTION E - ADVANCED CONCEPTS
==========================================================================================

================================================================================
Q24. Classify products into price tiers
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

           product_name  unit_price price_tier
0      Wireless Earbuds      1499.0  Mid-Range
1        Cotton T-Shirt       799.0     Budget
2           Smart Watch      2999.0  Mid-Range
3         Running Shoes      4599.0    Premium
4     Bluetooth Speaker      3499.0    Premium
5          Bedsheet Set      1299.0  Mid-Range
6          Laptop Stand       899.0     Budget
7  Cushion Covers (Set)       599.0     Budget

================================================================================
Q25. Count Delivered vs Not Delivered orders
================================================================================

C:\Users\prapt\AppData\Local\Temp\ipykernel_260860\877412675.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, connection))

   Delivered  Not_Delivered
0        6.0            5.0

==========================================================================================
Q26. ACID Properties
==========================================================================================

A - Atomicity
A transaction is completed fully or not at all.

C - Consistency
The database remains valid before and after every transaction.

I - Isolation
Transactions execute independently without interfering.

D - Durability
Once committed, changes are permanently stored.

Example:
In a bank transfer, money is deducted from one account
and credited to another. If any step fails, the entire
transaction is rolled back.


==========================================================================================
Q27. SQL Transaction
==========================================================================================

START TRANSACTION;

INSERT INTO orders
(order_id, customer_id, order_date, status, total_amount)
VALUES
(1011,102,CURDATE(),'Pending',1598.00);

INSERT INTO order_items
(item_id,order_id,product_id,quantity,unit_price,discount_pct)
VALUES
(16,1011,201,1,999.00,0),
(17,1011,203,1,599.00,0);

UPDATE products
SET stock_qty=stock_qty-1
WHERE product_id IN (201,203);

COMMIT;

If any statement fails before COMMIT,
ROLLBACK should be executed.