In [2]:
import os
print(os.getcwd())

C:\Users\prapt

In [3]:
os.listdir()

['.anaconda',
 '.bash_history',
 '.conda',
 '.condarc',
 '.continuum',
 '.eclipse',
 '.gitconfig',
 '.gnutls',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.p2',
 '.packettracer',
 '.viminfo',
 '.VirtualBox',
 '.vscode',
 '.vscode-shared',
 'anaconda3',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'assignment_01.ipynb',
 'assignment_1.ipynb',
 'Cisco Packet Tracer 9.0.0',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'eclipse',
 'Favorites',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{7a1cd578-7c5c-11f0-b65f-9cc7d300aa29}.TM.blf',
 'NTUSER.DAT{7a1cd578-7c5c-11f0-b65f-9cc7d300aa29}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{7a1cd578-7c5c-11f0-b65f-9cc7d300aa29}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'ScStore',
 'Searches',
 'SendTo',
 'Start Menu',
 'students.csv',
 'table1.csv',
 'table2.csv',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'urls.txt',
 'Videos',
 'VirtualBox VMs',
 'work']

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\prapt\OneDrive\Desktop\archive (1)\Combined_dataset.csv")

print(df)

     product_id           title  \
0       8376765     Lino Perros
1       9136281  Tommy Hilfiger
2      17633752           Lavie
3       1376949          F Gear
4      13939916       MYTRIDENT
..          ...             ...
995    13698258           KREDO
996    16896006           GUESS
997     1708108        GIORDANO
998    19280114        Fastrack
999    18601682         BOLDFIT

                                   product_description  rating  ratings_count  \
0                       Women Navy Blue Solid Backpack     3.8             15
1                    Unisex Navy Blue Striped Backpack     4.5             67
2                       Aries Women Pink Mini Backpack     4.4            226
3           Unisex Navy & Grey Printed Burner Backpack     4.4           1052
4                             Men Blue Solid Bath Robe     4.7             12
..                                                 ...     ...            ...
995  Men FORTE Silver Automatic Skeleton Analogue W...     3.5             11
996  Women White Patterned Dial & White Straps Anal...     5.0             22
997  Women Rose Gold-Toned Mirrored Analogue Watch ...     2.8              5
998  Men Black Brass Dial & Black Stainless Steel S...     4.3             17
999                           Purple Textured Yoga Mat     3.8            161

     initial_price  discount   final_price currency  \
0             3995      58.0   "₹3,995.00"      INR
1             2899      35.0   "₹2,899.00"      INR
2             2999      65.0   "₹2,999.00"      INR
3             1675      52.0   "₹1,675.00"      INR
4             2899      17.0   "₹2,899.00"      INR
..             ...       ...           ...      ...
995          11890      50.0  "₹11,890.00"      INR
996           8900      45.0   "₹8,900.00"      INR
997           7950      50.0   "₹7,950.00"      INR
998           3295      20.0   "₹2,636.00"      INR
999            699      31.0     "₹699.00"      INR

                                                images  ...  \
0    http://assets.myntassets.com/assets/images/837...  ...
1    http://assets.myntassets.com/assets/images/913...  ...
2    http://assets.myntassets.com/assets/images/176...  ...
3    http://assets.myntassets.com/assets/images/137...  ...
4    http://assets.myntassets.com/assets/images/pro...  ...
..                                                 ...  ...
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
0    {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1    {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2    {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3    {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4    {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
..                                                 ...                 ...
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                                              sizes  \
0               NaN                               [{"size":"Onesize"}]
1               NaN                               [{"size":"Onesize"}]
2               NaN                                     [{"size":"S"}]
3               NaN                               [{"size":"Onesize"}]
4               NaN  [{"size":"M","value":"45.0in","value_name":"Fr...
..              ...                                                ...
995             NaN                               [{"size":"Onesize"}]
996             NaN                               [{"size":"Onesize"}]
997             NaN                               [{"size":"Onesize"}]
998  Tru███m R███il                               [{"size":"Onesize"}]
999             NaN                                [{"size":"Medium"}]

                                                videos  \
0                                ["rw-8376765_cae700"]
1                                ["rw-9136281_cae700"]
2    ["https://videos.myntassets.com/assets/videos/...
3    ["https://videos.myntassets.com/assets/videos/...
4                                                  NaN
..                                                 ...
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                                      variations  \
0                                           [{}]
1                                        [{},{}]
2                            [{},{},{},{},{},{}]
3                                            NaN
4    [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
..                                           ...
995                                          NaN
996                                          NaN
997                    [{},{},{},{},{},{},{},{}]
998                                          NaN
999                                [{},{},{},{}]

                                            best_offer  \
0                                                   {}
1                                                   {}
2                                                   {}
3                                                   {}
4                                                   {}
..                                                 ...
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
0    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4    [{"offer_name":"10% Instant Discount on IndusI...  bath-robe
..                                                 ...        ...
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[1000 rows x 24 columns]

In [5]:
print("First 5 Rows:")
print(df.head())

First 5 Rows:
   product_id           title                         product_description  \
0     8376765     Lino Perros              Women Navy Blue Solid Backpack
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe

   rating  ratings_count  initial_price  discount  final_price currency  \
0     3.8             15           3995      58.0  "₹3,995.00"      INR
1     4.5             67           2899      35.0  "₹2,899.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
4     4.7             12           2899      17.0  "₹2,899.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/837...  ...
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
4  http://assets.myntassets.com/assets/images/pro...  ...

                                     amount_of_stars what_customers_said  \
0  {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN

  seller_name                                              sizes  \
0         NaN                               [{"size":"Onesize"}]
1         NaN                               [{"size":"Onesize"}]
2         NaN                                     [{"size":"S"}]
3         NaN                               [{"size":"Onesize"}]
4         NaN  [{"size":"M","value":"45.0in","value_name":"Fr...

                                              videos seller_information  \
0                              ["rw-8376765_cae700"]                NaN
1                              ["rw-9136281_cae700"]                NaN
2  ["https://videos.myntassets.com/assets/videos/...                NaN
3  ["https://videos.myntassets.com/assets/videos/...                NaN
4                                                NaN                NaN

                                    variations best_offer  \
0                                         [{}]         {}
1                                      [{},{}]         {}
2                          [{},{},{},{},{},{}]         {}
3                                          NaN         {}
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]         {}

                                         more_offers   category
0  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4  [{"offer_name":"10% Instant Discount on IndusI...  bath-robe

[5 rows x 24 columns]

In [6]:
print("\n Shape:")
print(df.shape)

 Shape:
(1000, 24)

In [7]:
print("\n Columns:")
print(df.columns)

 Columns:
Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [8]:
print("\n Dataset Information :")
print(df.info())

 Dataset Information :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB
None

In [9]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [10]:
df["discount"] = df["discount"].fillna(0)
print(df.isnull().sum())

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                    0
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [11]:
df["seller_name"] = df["seller_name"].fillna("Unknown")
df["seller_information"] = df["seller_information"].fillna("Unknown")
df["videos"] = df["videos"].fillna("Not Available")
df["variations"] = df["variations"].fillna("No Variations")
df["what_customers_said"] = df["what_customers_said"].fillna("No Reviews")

df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [12]:
filtered_df = df[df["rating"] > 4.0]

filtered_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Reviews,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Reviews,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Reviews,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,Unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Reviews,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Not Available,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

In [13]:
filtered_df.shape

(533, 24)

In [14]:
selected_df = filtered_df[
    [
        "product_id",
        "title",
        "rating",
        "initial_price",
        "discount",
        "final_price",
        "seller_name",
        "category"
    ]
]

selected_df.head()

,product_id,title,rating,initial_price,discount,final_price,seller_name,category
1,9136281,Tommy Hilfiger,4.5,2899,35.0,"""₹2,899.00""",Unknown,backpacks
2,17633752,Lavie,4.4,2999,65.0,"""₹2,999.00""",Unknown,backpacks
3,1376949,F Gear,4.4,1675,52.0,"""₹1,675.00""",Unknown,backpacks
4,13939916,MYTRIDENT,4.7,2899,17.0,"""₹2,899.00""",Unknown,bath-robe
5,17198778,H&M,4.5,1399,0.0,"""₹1,399.00""",H &███Hen███ & █████████eta█████████████████████,bathroom-accessories

In [15]:
selected_df.shape

(533, 8)

In [16]:
selected_df.duplicated().sum()

np.int64(0)

In [17]:
cleaned_df = selected_df.drop_duplicates()

In [18]:
cleaned_df.shape

(533, 8)

In [20]:
cleaned_df["final_price"].dtype

dtype('O')

In [22]:
cleaned_df["final_price"].head(10)

1     "₹2,899.00"
2     "₹2,999.00"
3     "₹1,675.00"
4     "₹2,899.00"
5     "₹1,399.00"
7     "₹2,999.00"
8     "₹2,999.00"
10    "₹2,199.00"
15    "₹1,199.00"
17    "₹6,329.00"
Name: final_price, dtype: object

In [23]:
cleaned_df["final_price"] = (
    cleaned_df["final_price"]
    .str.replace('"', '', regex=False)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [24]:
cleaned_df["final_price"].head()

1    2899.0
2    2999.0
3    1675.0
4    2899.0
5    1399.0
Name: final_price, dtype: float64

In [25]:
cleaned_df["final_price"].dtype

dtype('float64')

In [26]:
cleaned_df["discount_amount"] = (
    cleaned_df["initial_price"] - cleaned_df["final_price"]
)

In [27]:
cleaned_df[["initial_price","final_price","discount_amount"]].head()

   initial_price  final_price  discount_amount
1           2899       2899.0              0.0
2           2999       2999.0              0.0
3           1675       1675.0              0.0
4           2899       2899.0              0.0
5           1399       1399.0              0.0

In [28]:
cleaned_df["total_amount"] = cleaned_df["final_price"]

In [29]:
cleaned_df[["final_price", "total_amount"]].head()

   final_price  total_amount
1       2899.0        2899.0
2       2999.0        2999.0
3       1675.0        1675.0
4       2899.0        2899.0
5       1399.0        1399.0

In [32]:
cleaned_df.to_csv(
    "ecommerce_dataset_cleaned.csv",
    index=False
)

print("CSV file saved successfully!")

CSV file saved successfully!

In [33]:
import os

os.listdir()

['.anaconda',
 '.bash_history',
 '.conda',
 '.condarc',
 '.continuum',
 '.eclipse',
 '.gitconfig',
 '.gnutls',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.p2',
 '.packettracer',
 '.viminfo',
 '.VirtualBox',
 '.vscode',
 '.vscode-shared',
 'anaconda3',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'assignment_01.ipynb',
 'assignment_1.ipynb',
 'Cisco Packet Tracer 9.0.0',
 'cleaned_shopping_dataset.csv',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'eclipse',
 'ecommerce_dataset_cleaned.csv',
 'Favorites',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{7a1cd578-7c5c-11f0-b65f-9cc7d300aa29}.TM.blf',
 'NTUSER.DAT{7a1cd578-7c5c-11f0-b65f-9cc7d300aa29}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{7a1cd578-7c5c-11f0-b65f-9cc7d300aa29}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'ScStore',
 'Searches',
 'SendTo',
 'Start Menu',
 'students.csv',
 'table1.csv',
 'table2.csv',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'urls.txt',
 'Videos',
 'VirtualBox VMs',
 'work']